sudo: required
language: node_js
addons:
  apt:
    # needed for cypress https://github.com/cypress-io/cypress/issues/1526
    packages:
      - libgconf-2-4
node_js:
  - "10"
cache:
  bundler: false
  yarn: true
  directories:
    - .build-cache
    - ~/.cache
git:
  submodules: false
install: yarn install --frozen-lockfile --non-interactive --audit --silent

jobs:
  include:
    - stage: libs e2e tests
      name: "Libs E2E tests"
      script: yarn run e2e-libs:ci
    - stage: client e2e tests & build
      language: bash
      name: "Client E2E tests & build the docker image"
      node_js:
      services:
        - docker
      install: skip
      script: |
        set -e
        RELEASE_VERSION=latest ./make-web.sh
        docker run -d -p 3303:3303 flogo/flogo-web:latest eula-accept
        sudo apt install nodejs
        yarn run e2e-client:ci
